In [1]:
import pandas as pd

In [3]:
data = [[1, 'Alice'], [2, 'Bob'], [13, 'John'], [6, 'Alex']]
students = pd.DataFrame(data, columns=['student_id', 'student_name']).astype({'student_id':'Int64', 'student_name':'object'})
data = [['Math'], ['Physics'], ['Programming']]
subjects = pd.DataFrame(data, columns=['subject_name']).astype({'subject_name':'object'})
data = [[1, 'Math'], [1, 'Physics'], [1, 'Programming'], [2, 'Programming'], [1, 'Physics'], [1, 'Math'], [13, 'Math'], [13, 'Programming'], [13, 'Physics'], [2, 'Math'], [1, 'Math']]
examinations = pd.DataFrame(data, columns=['student_id', 'subject_name']).astype({'student_id':'Int64', 'subject_name':'object'})

students

   student_id student_name
0           1        Alice
1           2          Bob
2          13         John
3           6         Alex

In [4]:
subjects

  subject_name
0         Math
1      Physics
2  Programming

In [5]:
examinations

    student_id subject_name
0            1         Math
1            1      Physics
2            1  Programming
3            2  Programming
4            1      Physics
5            1         Math
6           13         Math
7           13  Programming
8           13      Physics
9            2         Math
10           1         Math

In [7]:
stud_sub_df = pd.merge(students,subjects, how = "cross")
stud_sub_df

    student_id student_name subject_name
0            1        Alice         Math
1            1        Alice      Physics
2            1        Alice  Programming
3            2          Bob         Math
4            2          Bob      Physics
5            2          Bob  Programming
6           13         John         Math
7           13         John      Physics
8           13         John  Programming
9            6         Alex         Math
10           6         Alex      Physics
11           6         Alex  Programming

In [28]:
stud_sub_df = pd.merge(students,subjects, how = "cross")

pd.merge(
    stud_sub_df,
    examinations,
    on=['student_id','subject_name'],
    how='left',
    suffixes=('', '_exm')
).groupby(['student_id','student_name','subject_name']).subject_name_exm.count().reset_index().sort_values(
    ['student_id','subject_name']
)

AttributeError: 'DataFrameGroupBy' object has no attribute 'subject_name_exm'

In [24]:
stud_sub_df = pd.merge(students, subjects, how="cross")

result = (
    pd.merge(
        stud_sub_df,
        examinations,
        on=['student_id', 'subject_name'],
        how='left',
        suffixes=('', '_exm')
    )
    .groupby(
        ['student_id', 'student_name', 'subject_name'],
        as_index=False
    )
    .agg(attended_exams=('student_id_exm', 'count'))
    .sort_values(['student_id', 'subject_name'])
)

result

KeyError: "Label(s) ['student_id_exm'] do not exist"

In [26]:
result = (
    stud_sub_df
    .merge(examinations, on=['student_id', 'subject_name'], how='left')
    .groupby(
        ['student_id', 'student_name', 'subject_name']
    )
    .size()
    .reset_index(name='attended_exams')
    .sort_values(['student_id', 'subject_name'])
)
result

    student_id student_name subject_name  attended_exams
0            1        Alice         Math               3
1            1        Alice      Physics               2
2            1        Alice  Programming               1
3            2          Bob         Math               1
4            2          Bob      Physics               1
5            2          Bob  Programming               1
6            6         Alex         Math               1
7            6         Alex      Physics               1
8            6         Alex  Programming               1
9           13         John         Math               1
10          13         John      Physics               1
11          13         John  Programming               1