In [4]:
import pandas as pd

In [5]:
data = [[1, 'Alice'], [7, 'Bob'], [11, 'Meir'], [90, 'Winston'], [3, 'Jonathan']]
employees = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'int64', 'name':'object'})
data = [[3, 1], [11, 2], [90, 3]]
employee_uni = pd.DataFrame(data, columns=['id', 'unique_id']).astype({'id':'int64', 'unique_id':'int64'})

In [6]:
employees

   id      name
0   1     Alice
1   7       Bob
2  11      Meir
3  90   Winston
4   3  Jonathan

In [7]:
employee_uni

   id  unique_id
0   3          1
1  11          2
2  90          3

In [9]:
pd.merge(employees,employee_uni, left_on = 'id' , right_on ='id', how = 'left')[['unique_id','name']]

   unique_id      name
0        NaN     Alice
1        NaN       Bob
2        2.0      Meir
3        3.0   Winston
4        1.0  Jonathan