In [1]:
import pandas as pd

In [3]:
data = [[1, 100, 2008, 10, 5000], [2, 100, 2009, 12, 5000], [7, 200, 2011, 15, 9000]]
sales = pd.DataFrame(data, columns=['sale_id', 'product_id', 'year', 'quantity', 'price']).astype({'sale_id':'Int64', 'product_id':'Int64', 'year':'Int64', 'quantity':'Int64', 'price':'Int64'})
data = [[100, 'Nokia'], [200, 'Apple'], [300, 'Samsung']]
product = pd.DataFrame(data, columns=['product_id', 'product_name']).astype({'product_id':'Int64', 'product_name':'object'})

In [4]:
sales

   sale_id  product_id  year  quantity  price
0        1         100  2008        10   5000
1        2         100  2009        12   5000
2        7         200  2011        15   9000

In [5]:
product

   product_id product_name
0         100        Nokia
1         200        Apple
2         300      Samsung

In [ ]:
pd.merge(sales,product,on='product_id',how ='left')[['product_name','year','price']]

  product_name  year  price
0        Nokia  2008   5000
1        Nokia  2009   5000
2        Apple  2011   9000